# Generated by Django 5.2.1 on 2025-05-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_departmentregion_departmenttype_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional category for this department",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.departmentcategory",
            ),
        ),
    ]
