# Generated by Django 5.2.1 on 2025-06-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_departmentcategory_department_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (3, "L3 (Rep)"),
                            (2, "L2 (Manager)"),
                            (1, "L1 (Director)"),
                        ],
                        help_text="Which approval level this limit is for",
                    ),
                ),
                (
                    "max_amount",
                    models.PositiveIntegerField(
                        help_text="Maximum quote total (₹) auto‐approved at this level"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="The department this limit applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_limits",
                        related_query_name="approval_limit",
                        to="profiles.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Limit",
                "verbose_name_plural": "Approval Limits",
                "ordering": ["department__name", "-level"],
                "unique_together": {("department", "level")},
            },
        ),
    ]
