# Generated by Django 5.2.1 on 2025-06-26 11:43

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_department_draft_quotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="draft_quotation",
            field=models.FileField(
                blank=True,
                help_text="Upload a DOCX (Microsoft Word) document up to 100 MB.",
                null=True,
                upload_to="departments/draft_quotations/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx"]
                    ),
                    profiles.models.validate_file_size,
                ],
            ),
        ),
    ]
