# Generated by Django 5.2.1 on 2025-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_alter_department_draft_quotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(
                blank=True,
                default="Not Defined Yet",
                help_text="User’s job title (e.g. Sales Manager).",
                max_length=100,
            ),
        ),
    ]
