# Generated by Django 5.2.1 on 2025-07-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_userprofile_job_title"),
        ("quotes", "0005_remove_quotetemplate_html_snippet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="quote_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the quotation template to use for this department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="quotes.quotetemplate",
            ),
        ),
    ]
