# Generated by Django 5.2.1 on 2025-05-26 17:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Installed size in kilowatts",
                        max_digits=6,
                        verbose_name="System Size (kW)",
                    ),
                ),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=12,
                        verbose_name="System Type",
                    ),
                ),
                (
                    "lead_quality",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("medium", "Medium"),
                            ("cold", "Cold"),
                        ],
                        max_length=6,
                        verbose_name="Lead Quality",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional notes", verbose_name="Remarks"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
