# Generated by Django 5.2.1 on 2025-05-26 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="lead_quality",
            field=models.CharField(
                choices=[("hot", "Hot"), ("medium", "Medium"), ("cold", "Cold")],
                default="medium",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="remarks",
            field=models.TextField(blank=True, help_text="Any additional notes"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="system_size",
            field=models.PositiveSmallIntegerField(
                help_text="Installed size in kilowatts (whole number only)"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="system_type",
            field=models.CharField(
                choices=[("residential", "Residential"), ("commercial", "Commercial")],
                default="residential",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
