# Generated by Django 5.2.1 on 2025-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_alter_lead_created_at_alter_lead_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="grid_type",
            field=models.CharField(
                blank=True,
                choices=[("on", "On-Grid"), ("off", "Off-Grid"), ("hybrid", "Hybrid")],
                help_text="If known, choose on-grid, off-grid or hybrid",
                max_length=6,
                null=True,
            ),
        ),
    ]
