# Generated by Django 5.2.1 on 2025-05-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_lead_grid_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total quoted amount in ₹",
                max_digits=10,
            ),
        ),
    ]
