# Generated by Django 5.2.1 on 2025-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_lead_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Total quoted amount in ₹",
                max_digits=10,
                null=True,
            ),
        ),
    ]
