# Generated by Django 5.2.1 on 2025-05-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_designation_remove_customer_name_customer_first_name_and_more",
        ),
        ("leads", "0005_alter_lead_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="customer",
            field=models.ForeignKey(
                default="",
                help_text="Which customer this lead belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="customers.customer",
            ),
            preserve_default=False,
        ),
    ]
