# Generated by Django 5.2.1 on 2025-05-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_designation_remove_customer_name_customer_first_name_and_more",
        ),
        ("leads", "0006_lead_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="customers.customer",
            ),
        ),
    ]
