# Generated by Django 5.2.1 on 2025-05-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0004_interest_customer"),
        ("leads", "0007_alter_lead_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="interest",
            field=models.ForeignKey(
                blank=True,
                help_text="If this lead was created from an Interest, store it here",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="interests.interest",
            ),
        ),
    ]
