# Generated by Django 5.2.1 on 2025-05-28 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0004_interest_customer"),
        ("leads", "0009_alter_lead_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="interest",
            field=models.OneToOneField(
                blank=True,
                help_text="If this lead was created from an Interest, store it here",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead",
                to="interests.interest",
            ),
        ),
    ]
