# Generated by Django 5.2.1 on 2025-05-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0010_alter_lead_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="total_amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total quoted amount in ₹ (whole rupees only)",
                null=True,
            ),
        ),
    ]
