# Generated by Django 5.2.1 on 2025-05-28 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0011_alter_lead_total_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers come first"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Person responsible for this lead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Current stage of this lead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leads.leadstage",
            ),
        ),
    ]
