# Generated by Django 5.2.1 on 2025-05-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0012_leadstage_lead_lead_manager_lead_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="grid_type",
            field=models.CharField(
                choices=[("on", "On-Grid"), ("off", "Off-Grid"), ("hybrid", "Hybrid")],
                help_text="If known, choose on-grid, off-grid or hybrid",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                default=1,
                help_text="Current stage of this lead",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="leads.leadstage",
            ),
            preserve_default=False,
        ),
    ]
