# Generated by Django 5.2.1 on 2025-06-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0017_alter_departmentassignmentpointer_department"),
        ("profiles", "0004_departmentcategory_department_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentassignmentpointer",
            name="department",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_pointer",
                to="profiles.department",
            ),
        ),
    ]
