# Generated by Django 5.2.1 on 2025-06-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0018_alter_departmentassignmentpointer_department"),
        ("profiles", "0005_approvallimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="department",
            field=models.ForeignKey(
                default=1,
                help_text="Assign this lead to a Sales department",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="profiles.department",
            ),
            preserve_default=False,
        ),
    ]
