# Generated by Django 5.2.1 on 2025-07-07 14:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_city_view_edit_users_city_view_only_users"),
        ("interests", "0006_alter_interest_phone_number"),
        ("leads", "0019_alter_lead_department"),
        ("profiles", "0009_department_quote_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLead",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "system_size",
                    models.PositiveSmallIntegerField(
                        help_text="Installed size in kilowatts (whole number only)"
                    ),
                ),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        default="residential",
                        max_length=12,
                    ),
                ),
                (
                    "lead_quality",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("medium", "Medium"),
                            ("cold", "Cold"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Any additional notes"),
                ),
                (
                    "grid_type",
                    models.CharField(
                        choices=[
                            ("on", "On-Grid"),
                            ("off", "Off-Grid"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="If known, choose on-grid, off-grid or hybrid",
                        max_length=6,
                    ),
                ),
                (
                    "total_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total quoted amount in ₹ (whole rupees only)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="customers.customer",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Assign this lead to a Sales department",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="profiles.department",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="If this lead was created from an Interest, store it here",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="interests.interest",
                    ),
                ),
                (
                    "lead_manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Person responsible for this lead",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Current stage of this lead",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leads.leadstage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical lead",
                "verbose_name_plural": "historical leads",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LeadChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Change Log",
                "verbose_name_plural": "Lead Change Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
