# Generated by Django 5.2.1 on 2025-05-25 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorizedinterestuser",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="authorizedinterestuser",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="authorizedinterestuser",
            name="role_type",
            field=models.CharField(
                choices=[("supervisor", "Supervisor"), ("member", "Member")],
                default="member",
                help_text="Supervisor can manage, Member can log interests",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="authorizedinterestuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorized_interest_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
