# Generated by Django 5.2.1 on 2025-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0002_alter_authorizedinterestuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="dials",
            field=models.IntegerField(
                default=0, help_text="How many times this lead was dialed"
            ),
        ),
    ]
