# Generated by Django 5.2.1 on 2025-05-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_designation_remove_customer_name_customer_first_name_and_more",
        ),
        ("interests", "0003_interest_dials"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Once set, this interest is locked to that customer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interests",
                to="customers.customer",
            ),
        ),
    ]
