# Generated by Django 5.2.1 on 2025-05-28 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0004_interest_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Enter a valid 10-digit phone number."
                    )
                ],
            ),
        ),
    ]
