# Generated by Django 5.2.1 on 2025-05-28 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0005_alter_interest_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="phone_number",
            field=models.CharField(
                help_text="Enter a 10-digit number",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Enter a valid 10-digit phone number."
                    )
                ],
            ),
        ),
    ]
