# Generated by Django 5.2.1 on 2025-05-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={},
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={"ordering": ["parent__id", "order"]},
        ),
        migrations.RemoveField(
            model_name="expense",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="expense",
            name="remarks",
            field=models.TextField(default="", help_text="Any notes or comments"),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="In ₹", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="expenses.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Subscription end date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(
                blank=True, help_text="Required if one-time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[("one_time", "One-Time"), ("subscription", "Subscription")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Subscription start date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
