# Generated by Django 5.2.1 on 2025-05-24 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0002_alter_expense_options_alter_expensecategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "ordering": ("parent__id", "name"),
                "verbose_name_plural": "Expense categories",
            },
        ),
        migrations.RemoveField(
            model_name="expense",
            name="category",
        ),
        migrations.RemoveField(
            model_name="expensecategory",
            name="order",
        ),
        migrations.AddField(
            model_name="expense",
            name="child_category",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"parent__isnull": False},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses_as_child",
                to="expenses.expensecategory",
                verbose_name="L2 category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="parent_category",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"parent__isnull": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses_as_parent",
                to="expenses.expensecategory",
                verbose_name="L1 category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Amount in ₹", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(
                blank=True,
                help_text="Required if this is a one-time expense",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[("one_time", "One-time"), ("subscription", "Subscription")],
                default="one_time",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="remarks",
            field=models.TextField(help_text="Describe this expense in brief"),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to create a top-level category",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="expenses.expensecategory",
            ),
        ),
    ]
