# Generated by Django 5.2.1 on 2025-05-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0003_alter_expense_options_alter_expensecategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={},
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "ordering": ["parent__id", "name"],
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
            },
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="In ₹", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="child_category",
            field=models.ForeignKey(
                help_text="Select an L2 (child) category.",
                limit_choices_to={"parent__isnull": False},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses_as_l2",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="end_date",
            field=models.DateField(blank=True, help_text="Subscription end", null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(
                blank=True, help_text="Required if One-Time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[("one_time", "One-Time"), ("subscription", "Subscription")],
                default="one_time",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="parent_category",
            field=models.ForeignKey(
                help_text="Select an L1 (parent) category.",
                limit_choices_to={"parent__isnull": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses_as_l1",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="remarks",
            field=models.TextField(help_text="Enter any notes or comments"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Subscription start", null=True
            ),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for a top-level (L1) category.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="expenses.expensecategory",
            ),
        ),
    ]
