# Generated by Django 5.2.1 on 2025-05-25 08:33

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_expense_created_by_expense_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional. PDF / JPG / PNG, up to 10 MB.",
                null=True,
                upload_to=expenses.models.attachment_upload_to,
                validators=[expenses.models.validate_attachment],
            ),
        ),
    ]
