# Generated by Django 5.2.1 on 2025-05-25 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_expense_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF/PNG/JPG (max 10 MB).",
                null=True,
                upload_to="expenses/%Y/%m/%d/",
            ),
        ),
        migrations.CreateModel(
            name="ExpenseRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("self", "Self-Service"),
                            ("viewer", "Global Viewer"),
                            ("editor", "Global Editor"),
                        ],
                        default="self",
                        help_text="What scope this user has for expenses",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_role",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
