# Generated by Django 5.2.1 on 2025-07-04 07:10

import oms_project.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_alter_expense_attachment_expenserole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF/PNG/JPG (max 10 MB).",
                null=True,
                storage=oms_project.storage_backends.MediaStorage(),
                upload_to="expenses/%Y/%m/%d/",
            ),
        ),
    ]
