# Generated by Django 5.2.1 on 2025-06-05 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_ping_before_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Number of minutes before the actual reminder_time to send the ping.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Settings",
                "verbose_name_plural": "Reminder Settings",
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="The primary key of that object"
                    ),
                ),
                (
                    "reminder_time",
                    models.DateTimeField(
                        help_text="Exact UTC datetime when this reminder is due."
                    ),
                ),
                (
                    "ping_before_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If set, notify this many minutes before reminder_time. Otherwise, use the global default in ReminderSettings.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DUE", "Due"),
                            ("PINGED", "Pinged"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="DUE",
                        help_text="Current state of this reminder.",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Brief description of why we’re reminding.",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MED", "Medium"), ("HIGH", "High")],
                        default="MED",
                        help_text="(Optional) Low / Medium / High priority.",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The type of object this reminder refers to (e.g. Lead, Customer, etc.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Which user should receive the ping / mark this as completed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "ordering": ["-reminder_time"],
            },
        ),
    ]
