# Generated by Django 5.2.1 on 2025-06-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Brand/Make",
                "verbose_name_plural": "Brands/Makes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryLevel1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "L1 Category",
                "verbose_name_plural": "L1 Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        help_text="E.g. “Each”, “Box”, “Kilogram”",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["unit_name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryLevel2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="Choose the L1 category this L2 belongs under",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="level2_categories",
                        to="items.categorylevel1",
                    ),
                ),
            ],
            options={
                "verbose_name": "L2 Category",
                "verbose_name_plural": "L2 Categories",
                "ordering": ["parent__name", "name"],
                "unique_together": {("parent", "name")},
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Full product name/description", max_length=200
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated 10-char alphanumeric SKU",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="Select the Brand/Make",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="items.brand",
                    ),
                ),
                (
                    "l1_category",
                    models.ForeignKey(
                        help_text="Select the L1 Category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="items.categorylevel1",
                    ),
                ),
                (
                    "l2_category",
                    models.ForeignKey(
                        help_text="Select the L2 Category (must belong under chosen L1)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="items.categorylevel2",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        help_text="Select the unit of measure",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="items.uom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["l1_category__name", "l2_category__name", "product_name"],
            },
        ),
        migrations.CreateModel(
            name="UPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Enter a UPC (barcode). Must be unique across Items.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upcs",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "UPC",
                "verbose_name_plural": "UPCs",
                "ordering": ["code"],
            },
        ),
    ]
