# Generated by Django 5.2.1 on 2025-06-01 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                help_text="User who first created this Item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                help_text="User who last modified this Item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
