# Generated by Django 5.2.1 on 2025-06-01 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_pricebook_pricerule_pricetier_availability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricebook",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pricerule",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pricetier",
            options={"ordering": ["min_quantity"]},
        ),
        migrations.AlterUniqueTogether(
            name="pricerule",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="pricebook",
            name="description",
        ),
        migrations.RemoveField(
            model_name="pricetier",
            name="max_quantity",
        ),
        migrations.RemoveField(
            model_name="pricetier",
            name="tier_price",
        ),
        migrations.AddField(
            model_name="pricerule",
            name="price_book",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_rules",
                to="items.pricebook",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricetier",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=2,
                help_text="Price applicable once quantity ≥ min_quantity.",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pricebook",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricebooks_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pricebook",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pricebook",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricebooks_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price per unit (or per kW, depending on unit_type).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricerules_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_rules",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="unit_type",
            field=models.CharField(
                choices=[("per_uom", "Per UOM"), ("per_kw", "Per kW")],
                default="per_uom",
                help_text="Whether this rule is per UOM or per kW.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="updated_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricerules_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pricetier",
            name="min_quantity",
            field=models.PositiveIntegerField(
                help_text="Minimum quantity for this tier."
            ),
        ),
        migrations.AlterField(
            model_name="pricetier",
            name="price_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiers",
                to="items.pricerule",
            ),
        ),
        migrations.RemoveField(
            model_name="pricerule",
            name="pricebook",
        ),
    ]
