# Generated by Django 5.2.1 on 2025-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_alter_pricebook_options_alter_pricerule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricerule",
            name="available",
            field=models.BooleanField(
                default=True, help_text="Is this item currently available for quoting?"
            ),
        ),
    ]
