# Generated by Django 5.2.1 on 2025-06-30 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_alter_pricerule_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricerule",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="pricerule",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="pricerule",
            constraint=models.UniqueConstraint(
                fields=("price_book", "item"), name="unique_pricebook_item"
            ),
        ),
    ]
