# Generated by Django 5.2.1 on 2025-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="full_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="primary_phone",
            field=models.CharField(max_length=20, verbose_name="Primary Phone"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="secondary_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Secondary Phone"
            ),
        ),
    ]
