# Generated by Django 5.2.1 on 2025-05-27 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_rename_full_name_customer_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="primary_phone",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="secondary_phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="customers.designation",
            ),
        ),
    ]
