# Generated by Django 5.2.1 on 2025-06-03 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_designation_remove_customer_name_customer_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customersource",
            name="color",
            field=models.CharField(
                default="#CCCCCC",
                help_text="Hex color code for this source (e.g. #A1B2C3).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#([0-9A-Fa-f]{6})$",
                        "Enter a valid hex color (e.g. '#A1B2C3').",
                    )
                ],
            ),
        ),
    ]
