# Generated by Django 5.2.1 on 2025-06-20 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_created_by_customer_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="view_edit_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can both view and edit customers in this city.",
                related_name="cities_view_edit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="view_only_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can view (but not edit) customers in this city.",
                related_name="cities_view_only",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
