# Generated by Django 5.2.1 on 2025-06-21 18:20

import django.core.validators
import visit_details.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitdetail",
            name="inspection_report",
            field=models.FileField(
                upload_to="visit_reports/%Y/%m/%d/",
                validators=[
                    visit_details.models.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                ],
            ),
        ),
    ]
