# Generated by Django 5.2.1 on 2025-06-23 14:23

import django.core.validators
import visit_details.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit_details", "0002_alter_visitdetail_inspection_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitimage",
            name="image",
            field=models.ImageField(
                upload_to="visit_images/%Y/%m/%d/",
                validators=[
                    visit_details.models.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
    ]
