# Generated by Django 5.2.1 on 2025-06-30 18:52

import django.core.validators
import oms_project.storage_backends
import visit_details.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit_details", "0003_alter_visitimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitdetail",
            name="inspection_report",
            field=models.FileField(
                storage=oms_project.storage_backends.MediaStorage(),
                upload_to="visit_reports/%Y/%m/%d/",
                validators=[
                    visit_details.models.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="visitimage",
            name="image",
            field=models.ImageField(
                storage=oms_project.storage_backends.MediaStorage(),
                upload_to="visit_images/%Y/%m/%d/",
                validators=[
                    visit_details.models.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
    ]
