# Generated by Django 5.2.1 on 2025-06-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="minimum_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Calculated minimum price based on rules",
                max_digits=12,
            ),
        ),
    ]
