# Generated by Django 5.2.1 on 2025-06-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_quote_minimum_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("approval_pending", "Approval Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("deleted", "Deleted"),
                ],
                default="approval_pending",
                max_length=20,
            ),
        ),
    ]
