# Generated by Django 5.2.1 on 2025-07-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_quote_approved_at_alter_quote_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A friendly name for this template", max_length=100
                    ),
                ),
                (
                    "pre_pdf",
                    models.FileField(
                        blank=True,
                        help_text="PDF to prepend before the HTML",
                        null=True,
                        upload_to="quote_templates/pre/",
                    ),
                ),
                (
                    "post_pdf",
                    models.FileField(
                        blank=True,
                        help_text="PDF to append after the HTML",
                        null=True,
                        upload_to="quote_templates/post/",
                    ),
                ),
                (
                    "html_snippet",
                    models.TextField(
                        blank=True,
                        help_text="HTML to insert between pre‐ and post‐PDFs",
                    ),
                ),
            ],
        ),
    ]
