# Generated by Django 5.2.1 on 2025-07-04 07:10

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_quotetemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotetemplate",
            name="html_snippet",
        ),
        migrations.AddField(
            model_name="quotetemplate",
            name="html_template",
            field=models.FileField(
                blank=True,
                help_text="HTML file for the main body of the quotation",
                null=True,
                upload_to="quote_templates/html/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    ),
                    profiles.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotetemplate",
            name="name",
            field=models.CharField(
                help_text="A human-friendly name for this template", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="quotetemplate",
            name="post_pdf",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF to append to the quotation",
                null=True,
                upload_to="quote_templates/post/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    profiles.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotetemplate",
            name="pre_pdf",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF to prepend to the quotation",
                null=True,
                upload_to="quote_templates/pre/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    profiles.models.validate_file_size,
                ],
            ),
        ),
    ]
