# Generated by Django 5.2.1 on 2025-07-04 13:32

import oms_project.storage_backends
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_remove_quotetemplate_html_snippet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotetemplate",
            name="html_template",
        ),
        migrations.AddField(
            model_name="quote",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Optional discount in ₹ (positive value).",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="quotetemplate",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="quotetemplate",
            name="post_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=oms_project.storage_backends.MediaStorage(),
                upload_to="quote_templates/post/",
            ),
        ),
        migrations.AlterField(
            model_name="quotetemplate",
            name="pre_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=oms_project.storage_backends.MediaStorage(),
                upload_to="quote_templates/pre/",
            ),
        ),
    ]
